#---------------------APPLICATION CONFIG------------------------------------#
spring.application.name=StockValuationBackend
server.port=8081
yahoo.base.url=http://127.0.0.1:5100/stock-val-api
#angular.app.url = http://localhost:4200
angular.app.url=https://stockvaluation.io
app.env=prod
logging.level.root=ERROR
#---------------------POSTGRES CONFIG ------------------------------------#
spring.datasource.url=jdbc:postgresql://localhost:5432/stockvaluation_io
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#---------------------DEFAULT USER CONFIG -----------------------------#
default.username=vikas.tiwari@oodles.io
default.password=1234
default.firstname=Vikas
default.lastname=Tiwari
default.contact=12356789
#------------------ Default Value Assumtion-----------------------------#
default.value_first=
default.value_second=
default.value_third=
default.value_fourth=
default.value_fifth = 