#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# Tables used by the Java valuation-service as deterministic reference datasets.
REFERENCE_TABLES = [
    "bond_rating",
    "cost_of_capital",
    "country_equity",
    "failure_rate",
    "industry_averages_global",
    "industry_averages_us",
    "input_stat_distribution",
    "large_bond_spread",
    "rdconvertor",
    "region_equity",
    "risk_free_rate",
    "sector_mapping",
    "small_bond_spread",
]

OBJECT_HEADER_RE = re.compile(r"^-- Name: (?P<name>.+?); Type: (?P<type>[^;]+);")
DATA_HEADER_RE = re.compile(r"^-- Data for Name: (?P<name>.+?); Type: TABLE DATA;")
INDEX_TABLE_RE = re.compile(r"\\bON\\s+public\\.(?P<table>[a-zA-Z0-9_]+)\\b")

HEADER = """--\n-- Reference-only PostgreSQL seed for valuation-service\n-- Source: .etl/stockvaluation_db_dump.sql (filtered to deterministic DCF reference tables)\n-- Generated by: scripts/extract_reference_seed_sql.py\n--\n\nSET statement_timeout = 0;\nSET lock_timeout = 0;\nSET idle_in_transaction_session_timeout = 0;\nSET transaction_timeout = 0;\nSET client_encoding = 'UTF8';\nSET standard_conforming_strings = on;\nSELECT pg_catalog.set_config('search_path', '', false);\nSET check_function_bodies = false;\nSET xmloption = content;\nSET client_min_messages = warning;\nSET row_security = off;\nSET default_tablespace = '';\nSET default_table_access_method = heap;\n\n"""


def iter_blocks(lines: list[str]):
    current_header = None
    current_lines: list[str] = []
    for line in lines:
        if line.startswith("-- Name: ") or line.startswith("-- Data for Name: "):
            if current_header is not None:
                yield current_header, current_lines
            current_header = line.rstrip("\n")
            current_lines = [line]
            continue
        if current_header is not None:
            current_lines.append(line)
    if current_header is not None:
        yield current_header, current_lines


def should_include_block(header: str, block_lines: list[str], tables: set[str]) -> bool:
    data_match = DATA_HEADER_RE.match(header)
    if data_match:
        return data_match.group("name") in tables

    obj_match = OBJECT_HEADER_RE.match(header)
    if not obj_match:
        return False

    obj_name = obj_match.group("name")
    obj_type = obj_match.group("type")
    seq_names = {f"{t}_id_seq" for t in tables}

    if obj_type == "TABLE":
        return obj_name in tables
    if obj_type in {"SEQUENCE", "SEQUENCE SET"}:
        return obj_name in seq_names
    if obj_type in {"CONSTRAINT", "FK CONSTRAINT"}:
        table_name = obj_name.split(" ", 1)[0]
        return table_name in tables
    if obj_type == "INDEX":
        block_sql = "".join(block_lines)
        idx_match = INDEX_TABLE_RE.search(block_sql)
        return bool(idx_match and idx_match.group("table") in tables)
    return False


def extract_reference_seed(source: Path, output: Path) -> dict[str, int]:
    lines = source.read_text(encoding="utf-8").splitlines(keepends=True)
    included_blocks: list[list[str]] = []
    stats = {
        "blocks": 0,
        "tables": 0,
        "table_data": 0,
        "sequences": 0,
        "sequence_sets": 0,
        "constraints": 0,
        "indexes": 0,
    }
    tables = set(REFERENCE_TABLES)

    for header, block in iter_blocks(lines):
        if not should_include_block(header, block, tables):
            continue
        included_blocks.append(block)
        stats["blocks"] += 1
        if header.startswith("-- Data for Name: "):
            stats["table_data"] += 1
            continue
        match = OBJECT_HEADER_RE.match(header)
        if not match:
            continue
        obj_type = match.group("type")
        if obj_type == "TABLE":
            stats["tables"] += 1
        elif obj_type == "SEQUENCE":
            stats["sequences"] += 1
        elif obj_type == "SEQUENCE SET":
            stats["sequence_sets"] += 1
        elif obj_type in {"CONSTRAINT", "FK CONSTRAINT"}:
            stats["constraints"] += 1
        elif obj_type == "INDEX":
            stats["indexes"] += 1

    if not included_blocks:
        raise RuntimeError("No blocks were extracted. Check dump format or table list.")

    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", encoding="utf-8") as f:
        f.write(HEADER)
        for block in included_blocks:
            for line in block:
                f.write(line)
            if not block[-1].endswith("\n"):
                f.write("\n")
            f.write("\n")

    return stats


def main() -> int:
    parser = argparse.ArgumentParser(description="Extract reference-only SQL seed from .etl/stockvaluation_db_dump.sql")
    parser.add_argument(
        "--source",
        default=".etl/stockvaluation_db_dump.sql",
        help="Path to full SQL dump (default: .etl/stockvaluation_db_dump.sql)",
    )
    parser.add_argument(
        "--output",
        default="docker/local/postgres/seeds/stockvaluation_reference_only.sql",
        help="Output path for filtered reference-only SQL",
    )
    args = parser.parse_args()

    source = Path(args.source)
    output = Path(args.output)
    if not source.exists():
        print(f"Source dump not found: {source}", file=sys.stderr)
        return 1

    stats = extract_reference_seed(source, output)
    print(f"Wrote reference-only seed: {output}")
    print(f"Reference tables: {', '.join(REFERENCE_TABLES)}")
    print(
        "Included blocks: "
        f"tables={stats['tables']}, "
        f"table_data={stats['table_data']}, "
        f"sequences={stats['sequences']}, "
        f"sequence_sets={stats['sequence_sets']}, "
        f"constraints={stats['constraints']}, "
        f"indexes={stats['indexes']}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
